AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB monitoring with CloudWatch Alarm and SNS notification

Parameters:
  AlertEmail:
    Type: String
    Default: avi.altcheh@ibm.com
    Description: Email address to receive DynamoDB error alerts

Resources:
  DynamoDBMonitorTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AviDynamoDBMonitorTable
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id 
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DynamoDBSystemErrorTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: DynamoDB System Errors Alert
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail

  DynamoDBSystemErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: "Alarm if DynamoDB table has any system errors"
      Namespace: AWS/DynamoDB
      MetricName: SystemErrors
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoDBMonitorTable
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref DynamoDBSystemErrorTopic
